# Generated by Django 3.2.2 on 2021-05-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='current_stock',
            field=models.IntegerField(),
        ),
    ]
