# Generated by Django 3.2.2 on 2021-05-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='products',
        ),
    ]
