# Generated by Django 3.2.2 on 2021-05-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210509_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_time',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
